### ISSUE TITLE
Build failure with optparse-applicative 0.13

### ISSUE THREAD

**Issue by snoyberg** [GregorySchwartz/blosum#2]
Preprocessing executable 'blosum' for blosum-0.1.1.2...
[1 of 1] Compiling Main             ( app/Main.hs, dist/build/blosum/blosum-tmp/Main.o )

app/Main.hs:47:10: error:
    • Variable not in scope: (<>) :: Mod f0 a0 -> Mod f1 a1 -> t1
    • Perhaps you meant one of these:
        data constructor ‘Seq.:>’ (imported from Data.Sequence),
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative)

app/Main.hs:48:10: error:
    • Variable not in scope: (<>) :: t1 -> Mod f2 a2 -> t0
    • Perhaps you meant one of these:
        data constructor ‘Seq.:>’ (imported from Data.Sequence),
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative)

app/Main.hs:49:10: error:
    • Variable not in scope:
        (<>) :: t0 -> Mod f3 a3 -> Mod OptionFields String
    • Perhaps you meant one of these:
        data constructor ‘Seq.:>’ (imported from Data.Sequence),
        ‘<$>’ (imported from Options.Applicative),

**Comment by GregorySchwartz** [comment]
Resolved.
